# Generated by Django 4.2.14 on 2024-07-30 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visaprocess', '0006_alter_visastatus_traking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaprocess.visaapplication')),
                ('visa_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaprocess.visastatus')),
            ],
        ),
    ]
