# Generated by Django 4.2.14 on 2024-08-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='interview_booking',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='visa_application',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='visa_status',
        ),
        migrations.AlterField(
            model_name='notification',
            name='massage',
            field=models.TextField(),
        ),
    ]
