# Generated by Django 4.2.14 on 2024-07-29 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visaprocess', '0006_alter_visastatus_traking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(unique=True)),
                ('max_interview', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slot', to='interview.interviewdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visa_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visaprocess.visaapplication')),
            ],
        ),
    ]
