# Generated by Django 4.2.15 on 2024-09-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0008_alter_visaapplication_applicant_signature_and_more'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visa_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='visaprocess.visaapplication'),
        ),
    ]
