# Generated by Django 4.2.15 on 2024-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterviewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_interview', models.IntegerField(default=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='NoInterview',
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
