# Generated by Django 4.2.14 on 2024-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interviewdate_interview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewbooking',
            name='is_complete',
        ),
        migrations.AlterField(
            model_name='interviewdate',
            name='interview_date',
            field=models.DateField(unique=True),
        ),
    ]
