# Generated by Django 4.2.14 on 2024-07-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_interviewbooking_is_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewdate',
            name='max_interview',
        ),
    ]
