# Generated by Django 4.2.14 on 2024-07-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_interviewdate_max_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdate',
            name='max_interview',
            field=models.IntegerField(default=1),
        ),
    ]
