# Generated by Django 4.2.15 on 2024-09-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_admininterviewinfo_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='interview_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Reschedule', 'Reschedule'), ('Cancel', 'Cancel')], default='Done', max_length=100),
        ),
    ]
