# Generated by Django 4.2.15 on 2024-09-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_appointment_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='slot_duration',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
