# Generated by Django 4.2.15 on 2024-09-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_scheduleslot_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedule_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview.scheduleslot'),
        ),
    ]
