# Generated by Django 4.2.14 on 2024-07-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('massage', models.TextField()),
                ('massage_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
