# Generated by Django 4.2.14 on 2024-07-14 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(choices=[('Tourist', 'Tourist'), ('Business', 'Business'), ('Student', 'Student'), ('Work', 'Work'), ('Medical', 'Medical'), ('Femily', 'Femily')], max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('passport_no', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
