# Generated by Django 4.2.15 on 2024-09-04 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import visaprocess.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('visa_type', models.CharField(choices=[('Tourist', 'Tourist'), ('Business', 'Business'), ('Student', 'Student'), ('Work', 'Work'), ('Medical', 'Medical'), ('Family', 'Family')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=30)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('passport_no', models.CharField(max_length=20)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('country_of_passport_issuance', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=40)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('state_province', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('purpose_of_visit', models.TextField()),
                ('planned_duration_of_stay', models.IntegerField()),
                ('accommodation_details', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=20)),
                ('emergency_contact_phone', models.IntegerField()),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('educational_background', models.CharField(max_length=255)),
                ('user_photo', models.FileField(upload_to=visaprocess.models.user_photo_upload_to)),
                ('travel_insurance', models.FileField(upload_to=visaprocess.models.travel_insurance_upload_to)),
                ('applicant_signature', models.FileField(upload_to=visaprocess.models.applicant_signature_upload_to)),
                ('passport_front_photo', models.FileField(blank=True, null=True, upload_to=visaprocess.models.passport_photo_upload_to)),
                ('passport_back_photo', models.FileField(upload_to=visaprocess.models.passport_photo_upload_to)),
                ('health_ensurence', models.FileField(upload_to=visaprocess.models.health_ensurence_upload_to)),
                ('is_approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('visa_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('schedule', 'schedule'), ('PoliceVerification', 'PoliceVerification'), ('AdminApprove', 'AdminApprove')], default='Pending', max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_statuses', to='visaprocess.visaapplication')),
            ],
            options={
                'verbose_name_plural': 'Visa Status',
                'ordering': ['update_at'],
            },
        ),
    ]
