# Generated by Django 4.2.14 on 2024-08-13 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('visa_type', models.CharField(choices=[('Tourist', 'Tourist'), ('Business', 'Business'), ('Student', 'Student'), ('Work', 'Work'), ('Medical', 'Medical'), ('Family', 'Family')], max_length=20)),
                ('gender', models.CharField(choices=[('Mail', 'Mail'), ('Femail', 'Femail'), ('Others', 'Others')], max_length=30)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('passport_no', models.CharField(max_length=20)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('country_of_passport_issuance', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=40)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('state_province', models.CharField(max_length=50)),
                ('purpose_of_visit', models.TextField()),
                ('planned_duration_of_stay', models.IntegerField()),
                ('accommodation_details', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=20)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('travel_insurance', models.FileField(upload_to='health/')),
                ('educational_background', models.CharField(max_length=255)),
                ('applicant_signature', models.FileField(upload_to='signeture/')),
                ('passport_photo', models.FileField(upload_to='passport/')),
                ('user_photo', models.FileField(upload_to='applicantPhoto/')),
                ('health_ensurence', models.FileField(upload_to='health/')),
                ('is_approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traking_id', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('visa_status', models.CharField(choices=[('Panding', 'Panding'), ('AdminApprove', 'AdminApprove'), ('PoliceVerification', 'PoliceVerification'), ('Approved', 'Approved')], default='Panding', max_length=100)),
                ('massage', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaprocess.visaapplication')),
            ],
            options={
                'verbose_name_plural': 'Visa Status',
                'ordering': ['update_at'],
            },
        ),
    ]
