# Generated by Django 4.2.14 on 2024-07-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VisaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traking_id', models.CharField(blank=True, max_length=10, null=True)),
                ('visa_status', models.CharField(choices=[('Panding', 'Panding'), ('AdminApprove', 'AdminApprove'), ('PoliceVerification', 'PoliceVerification'), ('Approved', 'Approved')], default='Panding', max_length=100)),
                ('massage', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaprocess.visaapplication')),
            ],
        ),
    ]
