# Generated by Django 4.2.14 on 2024-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=30),
        ),
    ]
