# Generated by Django 4.2.14 on 2024-07-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0002_visaapplication_is_modified_visastatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visastatus',
            options={'ordering': ['update_at']},
        ),
        migrations.AlterField(
            model_name='visastatus',
            name='traking_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
