# Generated by Django 4.2.7 on 2024-08-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0002_alter_visaapplication_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visastatus',
            name='massage',
        ),
        migrations.AddField(
            model_name='visastatus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
