# Generated by Django 4.2.15 on 2024-09-19 04:58

from django.db import migrations, models
import visaprocess.models


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0003_alter_visaapplication_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='applicant_signature',
            field=models.ImageField(upload_to=visaprocess.models.applicant_signature_upload_to),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='health_ensurence',
            field=models.ImageField(upload_to=visaprocess.models.health_ensurence_upload_to),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_back_photo',
            field=models.ImageField(upload_to=visaprocess.models.passport_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to=visaprocess.models.passport_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='travel_insurance',
            field=models.ImageField(upload_to=visaprocess.models.travel_insurance_upload_to),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='user_photo',
            field=models.ImageField(upload_to=visaprocess.models.user_photo_upload_to),
        ),
    ]
