# Generated by Django 4.2.14 on 2024-07-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0003_alter_visastatus_options_alter_visastatus_traking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visastatus',
            old_name='visa',
            new_name='visa_application',
        ),
    ]
