# Generated by Django 4.2.7 on 2024-08-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0003_remove_visastatus_massage_visastatus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visastatus',
            name='visa_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_statuses', to='visaprocess.visaapplication'),
        ),
    ]
