# Generated by Django 4.2.15 on 2024-09-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0004_alter_visaapplication_applicant_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='purpose_of_visit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
