# Generated by Django 4.2.7 on 2024-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0004_alter_visastatus_visa_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visastatus',
            old_name='traking_id',
            new_name='tracking_id',
        ),
        migrations.AlterField(
            model_name='visastatus',
            name='visa_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('AdminApprove', 'AdminApprove'), ('PoliceVerification', 'PoliceVerification'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
    ]
