# Generated by Django 4.2.14 on 2024-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0004_rename_visa_visastatus_visa_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visastatus',
            name='traking_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
