# Generated by Django 4.2.15 on 2024-09-03 07:47

from django.db import migrations, models
import visaprocess.models


class Migration(migrations.Migration):

    dependencies = [
        ('visaprocess', '0008_alter_visaapplication_applicant_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visaapplication',
            old_name='passport_photo',
            new_name='passport_back_photo',
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='passport_front_photo',
            field=models.FileField(blank=True, null=True, upload_to=visaprocess.models.passport_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
